name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.repository_owner != github.event.pull_request.head.repo.owner.login }}

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up JDK 17
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          java-version: 17
          distribution: 'adopt'

      - uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3.3.3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B -Dchangelist=-${{github.run_number}} clean verify

      - name: Extract version
        run: |
          VERSION=$(cat pom.xml | grep '<revision' | grep -o -E '[0-9]+\.[0-9]+(\.[0-9]+)?')
          echo "${VERSION}-${{github.run_number}}" > target/version.txt

      - name: Upload plugin
        uses: actions/upload-artifact@1eb3cb2b3e0f29609092a73eb033bb759a334595 # v4.1.0
        with:
          name: additional-identities-plugin
          path: |
            target/additional-identities-plugin.hpi
            target/version.txt

  release:
    needs: [build]

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Git user
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Download plugin
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
        with:
          name: additional-identities-plugin
          path: .

      - name: Create git tag
        run: |
          v=$(cat version.txt)
          git tag v$v
          git push origin v$v
          echo "VERSION=${v}" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          files: additional-identities-plugin.hpi
          name: ${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          body: Relase v${{ env.VERSION }}
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
